#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# Every path below is relative to the repo root, and the verification stage
# resolves firebase-admin out of ./node_modules, so refuse to run elsewhere.
if [[ ! -f .firebaserc ]]; then
  printf '\n  Run this from the repo root - no .firebaserc here.\n\n' >&2
  exit 1
fi

PROJECT_ID=$(node -e 'process.stdout.write(require("./.firebaserc").projects.default)' 2>/dev/null || echo "gp-client-trainer-portal")
KEY_DIR="secrets"
KEY_FILE="$KEY_DIR/service-account.json"

banner "GreenPulse admin credentials"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Confirm the Firebase project"
say "Ticket 02 renames the workouts collection to sessions. That migration"
say "runs under the Admin SDK, which needs a service account key this repo"
say "does not have yet."
printf '\n'
note "project, from .firebaserc:  $PROJECT_ID"
note "key will be saved to:       $KEY_FILE"
printf '\n'
warn "An Admin SDK key bypasses firestore.rules completely and has full"
warn "read/write access to real client data. Treat it like a password."
printf '\n'
if ! confirm "Is $PROJECT_ID the project you want to set up?"; then
  say "Nothing changed. Fix .firebaserc first, then re-run."
  exit 0
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Generate a service account key"
say "Firebase hands you the private key as a one-time JSON download. It is"
say "never shown again, so a lost key is replaced rather than recovered."
printf '\n'
open_url "https://console.firebase.google.com/project/$PROJECT_ID/settings/serviceaccounts/adminsdk"
printf '\n'
step "The page opens on Project settings, Service accounts tab."
step "Under 'Firebase Admin SDK', click 'Generate new private key'."
step "Confirm 'Generate key'. A .json file downloads."
printf '\n'
note "Tip: drag the downloaded file into this terminal to paste its path."
printf '\n'
ask SA_DOWNLOAD "Full path to the downloaded .json:"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Install the key, and keep it out of git"

# Normalise what a human actually pastes: quotes from a drag-and-drop, and
# Windows backslashes, which Git Bash cannot stat.
SA_SRC="${SA_DOWNLOAD%\"}"; SA_SRC="${SA_SRC#\"}"
SA_SRC="${SA_SRC%\'}";      SA_SRC="${SA_SRC#\'}"
SA_SRC=$(printf "%s" "$SA_SRC" | tr "\\" "/")

if [[ ! -f "$SA_SRC" ]]; then
  warn "No file at: $SA_SRC"
  say "Re-run the wizard once you have the path."
  exit 1
fi

KEY_PROJECT=$(node -e 'const k=require(process.argv[1]); process.stdout.write(k.project_id||"")' "$SA_SRC" 2>/dev/null || echo "")
if [[ -z "$KEY_PROJECT" ]]; then
  warn "That file has no project_id, so it is not a service account key."
  exit 1
fi
if [[ "$KEY_PROJECT" != "$PROJECT_ID" ]]; then
  warn "That key belongs to '$KEY_PROJECT', not '$PROJECT_ID'."
  confirm "Use it anyway?" || exit 1
fi

mkdir -p "$KEY_DIR"
cp "$SA_SRC" "$KEY_FILE"
chmod 600 "$KEY_FILE" 2>/dev/null || true
printf '  %s✓ saved%s %s\n' "$GREEN" "$RESET" "$KEY_FILE"

# .gitignore already covers *.key and *.pem, but a service account arrives as
# .json, so ignore the directory wholesale rather than trusting a filename.
if grep -qE '^secrets/?$' .gitignore 2>/dev/null; then
  note "secrets/ is already in .gitignore"
else
  printf '\n# Admin SDK service account keys - never commit these\nsecrets/\n' >> .gitignore
  printf '  %s✓ added%s secrets/ to .gitignore\n' "$GREEN" "$RESET"
fi

write_env GOOGLE_APPLICATION_CREDENTIALS "$KEY_FILE"
note "Deliberately not EXPO_PUBLIC_, so it is never bundled into the app."
note "Same rule YOUTUBE_API_KEY follows."
printf '\n'
say "Once this is done, delete the original download:"
note "  $SA_SRC"
printf '\n'
pause "Press Enter to verify the key"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Verify, and record the pre-migration baseline"
say "This proves the key reaches Firestore, and prints the record count that"
say "ticket 02 has to check before it deletes anything."
printf '\n'

if ! node -e 'require.resolve("firebase-admin")' >/dev/null 2>&1; then
  warn "firebase-admin is not installed."
  say "Run:  npm install --save-dev firebase-admin"
  say "then re-run this wizard - it keeps the values already saved."
  SKIPPED+=("verify the key: firebase-admin was not installed")
elif KEY_PATH="$PWD/$KEY_FILE" node -e '
    const admin = require("firebase-admin")
    admin.initializeApp({ credential: admin.credential.cert(require(process.env.KEY_PATH)) })
    const db = admin.firestore()
    Promise.all([db.collection("workouts").get(), db.collection("sessions").get()])
      .then(([w, s]) => {
        console.log("  workouts documents: " + w.size)
        console.log("  sessions documents: " + s.size + (s.size ? "   <- migration may already have run" : ""))
        process.exit(0)
      })
      .catch((e) => { console.error("  " + e.message); process.exit(1) })
  '; then
  printf '\n  %s✓ the key works%s\n' "$GREEN" "$RESET"
  note "Write the workouts count down. The migration must end with the same"
  note "number of sessions documents before anything is deleted."
else
  warn "Could not read Firestore with that key."
  SKIPPED+=("verify the key: the Firestore read failed")
fi

printf '\n'
pause "Press Enter for the summary"

finish
